name: CodeCov

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug
      
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install Dependencies
        uses: php-actions/composer@v6
      
      - name: PHPStan analysis
        run: vendor/bin/phpstan analyse
      
      - name: Pest Test
        run: vendor/bin/pest tests/ -c phpunit.xml  --coverage --coverage-clover clover.xml
      
      - name: Pest Type Coverage
        run: vendor/bin/pest tests/ -c phpunit.xml  --type-coverage --min=100

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Pint test
        run: vendor/bin/pint --test
